version: '3'
services:
  moodle:
    image: 'bitnami/moodle:4.1.2'
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - MOODLE_DATABASE_TYPE=mysqli
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_PORT=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=secret
      - MOODLE_DATABASE_NAME=moodle
    volumes:
      - moodledata:/var/www/html/moodledata
    networks:
      - moodlenet

  db:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - moodlenet

volumes:
  moodledata:
  dbdata:

networks:
  moodlenet:
    driver: bridge